config/routes.rb
Rails.application.routes.draw do
  resources :zombis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/zombi.rb
class Zombi < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/zombis_controller.rb
class ZombisController < ApplicationController
  before_action :set_zombi, only: [:show, :edit, :update, :destroy]

  # GET /zombis
  # GET /zombis.json
  def index
    @zombis = Zombi.all
  end

  # GET /zombis/1
  # GET /zombis/1.json
  def show
  end

  # GET /zombis/new
  def new
    @zombi = Zombi.new
  end

  # GET /zombis/1/edit
  def edit
  end

  # POST /zombis
  # POST /zombis.json
  def create
    @zombi = Zombi.new(zombi_params)

    respond_to do |format|
      if @zombi.save
        format.html { redirect_to @zombi, notice: 'Zombi was successfully created.' }
        format.json { render :show, status: :created, location: @zombi }
      else
        format.html { render :new }
        format.json { render json: @zombi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombis/1
  # PATCH/PUT /zombis/1.json
  def update
    respond_to do |format|
      if @zombi.update(zombi_params)
        format.html { redirect_to @zombi, notice: 'Zombi was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombi }
      else
        format.html { render :edit }
        format.json { render json: @zombi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombis/1
  # DELETE /zombis/1.json
  def destroy
    @zombi.destroy
    respond_to do |format|
      format.html { redirect_to zombis_url, notice: 'Zombi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombi
      @zombi = Zombi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombi_params
      params.require(:zombi).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zombis_helper.rb
module ZombisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/zombis/_form.html.erb
<%= form_for(zombi) do |f| %>
  <% if zombi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombi.errors.count, "error") %> prohibited this zombi from being saved:</h2>

      <ul>
      <% zombi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombis/edit.html.erb
<h1>Editing Zombi</h1>

<%= render 'form', zombi: @zombi %>

<%= link_to 'Show', @zombi %> |
<%= link_to 'Back', zombis_path %>

app/views/zombis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zombis.each do |zombi| %>
      <tr>
        <td><%= zombi.name %></td>
        <td><%= zombi.age %></td>
        <td><%= zombi.email %></td>
        <td><%= zombi.rotten %></td>
        <td><%= link_to 'Show', zombi %></td>
        <td><%= link_to 'Edit', edit_zombi_path(zombi) %></td>
        <td><%= link_to 'Destroy', zombi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombi', new_zombi_path %>

app/views/zombis/new.html.erb
<h1>New Zombi</h1>

<%= render 'form', zombi: @zombi %>

<%= link_to 'Back', zombis_path %>

app/views/zombis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombi.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombi.age %>
</p>

<%= link_to 'Edit', edit_zombi_path(@zombi) %> |
<%= link_to 'Back', zombis_path %>